Controllers/InventoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OfficeOpenXml;
using SDK.Shopee;
using System;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

/*

    **  nhập hàng    **
mua                     - slug = 101 x nhập kho
khách trả               - slug = 102 x  nhập kho
nhập tái chế sl       - slug = 103 x nhập kho sl, không tính giá

    **  xuất hàng   **
huỷ                      -  slug = 201 x    xuất kho    xx tính giá
trả nhà cung cấp    - slug = 202 x  xuất kho    xx tính giá
xuất tái chế sl           - slug = 203 x xuất kho, không tính giá

    **  bán hàng shopee   **
giao hàng      - slug = 301  -   OrderStatus = 1    > xuất kho
hoàn thành    - slug = 302  -   OrderStatus = 2 xx tính giá
huỷ                - slug = 303  -   OrderStatus = 9    > nhập kho slug = 604 (nhập luân chuyển/ chỉnh số lượng)

    **  bán hàng cửa hàng   **
giao hàng      - slug = 401  -   OrderStatus = 1    > xuất kho
hoàn thành    - slug = 402  -   OrderStatus = 2 xx tính giá
huỷ                - slug = 403  -   OrderStatus = 9    > nhập kho  slug = 604 (nhập luân chuyển/ chỉnh số lượng)

    **  sản xuất    **
nhap -  slug = 501 x    nhập kho
xuat -  slug = 502 x    xuất kho

 */

namespace ShopCP.Controllers
{
    public class InventoryController : BaseController
    {
        private readonly ILogger<InventoryController> _Logger;
        public InventoryController(ILogger<InventoryController> logger)
        {
            _Logger = logger;
        }


        #region [--INPUT--]
        [Route("don-mua-hang/{OrderKey}/{Slug}")]
        public IActionResult Edit_Input(string OrderKey, int Slug)
        {
            string Title = "";
            var zInfo = new Purchase_Info(OrderKey);
            var zOrder = zInfo.Purchase;
            zOrder.OrderDate = DateTime.Now;
            zOrder.ListItem = Purchase_Item_Data.List(UserLog.PartnerNumber, OrderKey, out _);
            zOrder.Slug = Slug;

            if (Slug == 101)
            {
                zOrder.OrderID = "INT-" + TN_Utils.RandomPassword().ToUpper();
                Title = "Nhập mua hàng ";
            }
            if (Slug == 102)
            {
                zOrder.OrderID = "RTN-" + TN_Utils.RandomPassword().ToUpper();
                Title = "Khách trả hàng ";
            }

            if (zInfo.Code == "404")
            {
                zOrder.OrderKey = OrderKey;
                ViewBag.Record = "IsNew";
                Title = Title + "(Mới)";
            }
            else
            {
                ViewBag.Record = "IsUpdate";
                Title = Title + "(Điều chỉnh)";
            }
            ViewBag.Title = Title;
            HttpContext.Session.SetString(OrderKey, JsonConvert.SerializeObject(zOrder));
            return View("~/Views/Inventory/Input/Edit.cshtml", zOrder);
        }
        [Route("danh-sach-don-mua-hang/{Slug}")]
        public IActionResult List_Input(int Slug)
        {
            string Title = "";
            if (Slug == 101)
            {
                Title = "Nhập mua hàng ";
            }
            if (Slug == 102)
            {
                Title = "Khách trả hàng ";
            }
            ViewBag.Title = Title;
            ViewBag.List = Purchase_Data.List(UserLog.PartnerNumber, Slug, out _);
            return View("~/Views/Inventory/Input/List.cshtml");
        }
        [HttpPost]
        public JsonResult Delete_Input(string OrderKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Purchase_Info();
            zInfo.Purchase.OrderKey = OrderKey;
            zInfo.Delete();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message;
            }

            return Json(zResult);
        }
        public JsonResult Save_Input(string OrderKey, string inputId, string inputDate, string VendorName, string VendorAddress, string Description, string TotalMoney, int Slug)
        {
            var zResult = new ServerResult();
            if (!DateTime.TryParseExact(inputDate, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime zDate))
            {
                zResult.Success = false;
                zResult.Message = "Sai định dạng ngày !.";
                return Json(zResult);
            }

            try
            {
                #region [Save Input]
                string sPurchase = HttpContext.Session.GetString(OrderKey);
                var zPurchase = JsonConvert.DeserializeObject<Purchase_Model>(sPurchase);
                int Count = 0;
                if (Slug == 101)
                {
                    foreach (var item in zPurchase.ListItem)
                    {

                        if (item.ItemMoney == 0)
                        {
                            Count++;
                        }
                    }
                }
                if (Count > 0)
                {
                    zResult.Success = false;
                    zResult.Message = "Giá nhập hàng không thể bằng 0!.";
                    return Json(zResult);
                }
                zPurchase.Description = Description.ExTrim();
                zPurchase.OrderID = inputId.ExTrim();
                zPurchase.VendorAddress = VendorAddress.ExTrim();
                zPurchase.VendorName = VendorName.ExTrim();
                zPurchase.TotalMoney = TotalMoney.ToDouble();
                zPurchase.OrderDate = zDate;
                zPurchase.Slug = Slug;    // "mua hàng"
                zPurchase.PartnerNumber = UserLog.PartnerNumber;
                zPurchase.CreatedName = UserLog.UserName;
                zPurchase.ModifiedName = UserLog.UserName;
                zPurchase.CreatedBy = UserLog.UserKey;
                zPurchase.ModifiedBy = UserLog.UserKey;
                #endregion

                //save data
                Purchase_Info zInfo = new(OrderKey);
                zInfo.Purchase = zPurchase;
                if (zInfo.Code == "404")
                {
                    zInfo.Purchase.OrderKey = OrderKey;
                    zInfo.Create_ClientKey();
                }
                else
                {
                    zInfo.Update();
                }

                if (zInfo.Code == "200" ||
                    zInfo.Code == "201")
                {
                    #region [Save Child]
                    zInfo.DeleteItem();
                    foreach (var item in zPurchase.ListItem)
                    {
                        item.OrderKey = OrderKey;
                        item.PartnerNumber = UserLog.PartnerNumber;
                        item.CreatedName = UserLog.UserName;
                        item.ModifiedName = UserLog.UserName;
                        item.CreatedBy = UserLog.UserKey;
                        item.ModifiedBy = UserLog.UserKey;

                        Purchase_Item_Info zItemInfo = new();
                        zItemInfo.Purchase_Item = item;
                        zItemInfo.Create_ServerKey();

                        if (zItemInfo.Code != "200" &&
                            zItemInfo.Code != "201")
                        {
                            zResult.Success = false;
                            zResult.Message = "Lưu Item: " + zItemInfo.Message.GetFirstLine();
                            break;
                        }
                        else
                        {
                            zResult.Success = true;
                        }
                    }
                    #endregion

                    //nếu là mua hàng thi tự động lập phiếu chi
                    if (zResult.Success && 
                        zPurchase.Slug == 101)
                    {
                        zResult.Success = TN_Mics.Create_Payment(zPurchase, out string Message);
                        zResult.Message = Message;
                    }
                }
                else
                {
                    zResult.Success = false;
                    zResult.Message = zInfo.Message.GetFirstLine();
                }

                //clear session
                HttpContext.Session.Remove(OrderKey);
            }
            catch (Exception ex)
            {
                _Logger.LogError(ex.ToString());
                ViewBag.Error = ex.ToString();
                zResult.Success = false;
                zResult.Message = "TempData error vui lòng liên hệ IT";
            }

            return Json(zResult);
        }
        [HttpPost]
        public IActionResult Add_Item(string Id, string OrderKey)
        {
            Purchase_Model zPurchase = new();
            try
            {
                string sPurchase = HttpContext.Session.GetString(OrderKey);

                if (!string.IsNullOrEmpty(sPurchase))
                {
                    zPurchase = JsonConvert.DeserializeObject<Purchase_Model>(sPurchase);
                }
                else
                {
                    zPurchase = new Purchase_Model();
                }

                Purchase_Item_Model zItem = zPurchase.ListItem.SingleOrDefault(s => s.ItemKey == Id);
                if (zItem != null)
                {
                    zItem.ItemQty++;
                    zItem.ItemMoney = zItem.ItemQty * zItem.ItemPrice;
                }
                else
                {
                    zItem = new Purchase_Item_Model();
                    var Product = new Product_Info(Id).Product;
                    zItem.ItemKey = Product.ProductKey;
                    zItem.ItemName = Product.ProductName;
                    zItem.ItemPhoto = Product.PhotoPath;

Views/Inventory/Output/Edit.cshtml
@model Order_Model
@{
    var ShopeeOrder = new SDK.Shopee.Root_OrderInfo.Data();
    if (ViewBag.ShopeeOrder != null)
    {
        ShopeeOrder = ViewBag.ShopeeOrder as SDK.Shopee.Root_OrderInfo.Data;
    }
    string _UrlImg = "https://cf.shopee.vn/file/";

    double total = 0;
    foreach (var rec in ShopeeOrder.order_items)
    {
        total += (rec.amount * rec.item_price.ToDouble());
    }

    total += ShopeeOrder.shipping_fee.ToDouble();
}
<header class="page-header">
    <h2 class="text-primary">Điều chỉnh đơn hàng xuất bán</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
<div class="action-buttons-fixed">
    <div class="row">
        <div class="col-6">
            <div class="accordion accordion-primary" id="accordion">
                <div class="card border card-default">
                    <div class="card-header">
                        <h4 class="card-title m-0">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#collapse1One">
                                Đơn hàng shopee số: @Model.S_OrderID
                            </a>
                        </h4>
                    </div>
                    <div id="collapse1One" class="collapse show" data-parent="#accordion">
                        <div class="card-body">
                            <div class="form-group-sm mb-2">
                                <p class="mb-1">Khách hàng: @ShopeeOrder.buyer_address_name</p>
                                <p class="mb-1">SĐT:@ShopeeOrder.buyer_address_phone</p>
                                <p class="mb-1">Địa chỉ: @ShopeeOrder.shipping_address</p>
                                <p class="mb-1">Vận chuyển: @ShopeeOrder.actual_carrier</p>
                            </div>
                            <div class="form-group-sm mb-2">
                                <label class="font-weight-bolder">Nội dung hàng:</label>
                                @for (int i = 0; i < ShopeeOrder.order_items.Count; i++)
                                {
                                    var rec = ShopeeOrder.order_items[i];
                                    var ex = rec.item_model;
                                    var img = _UrlImg + rec.product.images[0] + "_tn";

                                    <div class="d-flex mb-2">
                                        <img class="imgShopee" src="@img" />
                                        <div class="float-left">
                                            <b>@rec.amount X </b>
                                            @rec.product.name
                                            @if (ex.name.Length > 0)
                                            {
                                                <br /><small>Phân loại: @ex.name</small>
                                            }
                                        </div>
                                    </div>
                                }
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label class="font-weight-bolder col-6">Người mua thanh toán:</label>
                                    <label class="font-weight-bolder col-6 text-right number">@total</label>
                                </div>
                                <div class="row">
                                    <label class="font-weight-bolder col-6">Cộng tiền hàng:</label>
                                    <label class="font-weight-bolder col-6 text-right number">@(total - ShopeeOrder.shipping_fee.ToDouble())</label>
                                </div>
                                <div class="row">
                                    <label class="font-weight-bolder col-6">Phí Shopee:</label>
                                    <label class="font-weight-bolder col-6 text-right number">@ShopeeOrder.card_txn_fee_info.card_txn_fee.ToDouble()</label>
                                </div>
                                <div class="row">
                                    <label class="font-weight-bolder col-6 text-danger">Thực thu:</label>
                                    <label class="font-weight-bolder col-6 text-danger text-right number">@(total - ShopeeOrder.shipping_fee.ToDouble() - ShopeeOrder.card_txn_fee_info.card_txn_fee.ToDouble())</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card border card-default">
                    <div class="card-header">
                        <h4 class="card-title m-0">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target="#collapse1Two">
                                Đơn hàng đã xuất bán
                            </a>
                        </h4>
                    </div>
                    <div id="collapse1Two" class="collapse show" data-parent="#accordion">
                        <div class="card-body">
                            <div class="form-group-sm mb-2 row align-items-center">
                                <div class="col-lg-12">
                                    <input type="text" id="txt_orderid" class="form-control" placeholder="Mã đơn hàng" asp-for="OrderID" />
                                </div>
                            </div>
                            <div class="form-group-sm mb-2 row align-items-center">
                                <div class="col-lg-12">
                                    <textarea id="txt_description" class="form-control" placeholder="Ghi chú" asp-for="Description"></textarea>
                                </div>
                            </div>
                            <div id="table_item">
                                @await Html.PartialAsync("~/Views/Inventory/Output/_Table_Item.cshtml", Model)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="input-group">
                                <input type="text" class="form-control" id="txt_productName">
                                <button class="btn btn-success" type="button" onclick="getProduct()">
                                    <i class="fas fa-filter"></i>
                                    Lọc
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="nano" style="height:100vh">
                                <div class="nano-content" id="divProduct">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row action-buttons">
        <div class="col-12">
            <button id="btn_Confirm" type="button" class="btn btn-primary float-right" onclick="saveCart();">
                Cập nhật
            </button>
            <a class="btn btn-outline-primary" role="button" onclick="Open('@Model.OrderKey', 'k80')">K80</a>
            <a class="btn btn-outline-primary" role="button" onclick="Open('@Model.OrderKey', 'k58')">K58</a>
            <a class="btn btn-outline-secondary" id="btn_Cancel" onclick="Utils.BackWithRefresh(); return false;">
                Hoàn tác & trở về
            </a>
        </div>
    </div>
</div>
<input id="txt_orderkey" type="hidden" asp-for="OrderKey" />
<div id="modal" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
</div>
@section scripts{
    <script>
        var Url_Search_Product = "@Url.Action("Search_Product", "Inventory")";
        var Url_Add_Item = "@Url.Action("Add_Item_Output", "Inventory")";
        var Url_Delete_Item = "@Url.Action("Del_Item_Output", "Inventory")";
        var Url_Remove_Item = "@Url.Action("Remove_Item_Output", "Inventory")";
        var Url_Save_Order = "@Url.Action("Save_Output", "Inventory")";
        var Url_Qty_Item = "@Url.Action("Qty_Item_Output", "Inventory")";
        var Url_Check_Item = "@Url.Action("Check_Item_Output", "Inventory")";
        getProduct();
        function getProduct() {
            var name = $("#txt_productName").val();
            $.ajax({
                url: Url_Search_Product,
                type: "GET",
                data: {
                    "name": name,
                },
                beforeSend: function () {
                    $("#divProduct").empty();
                },
                success: function (r) {
                    $("#divProduct").append(r);
                },
                error: function (err) {

                },
                complete: function () {

                }
            });
        }
        function addCart(id) {
            $.ajax({
                url: Url_Check_Item,
                type: "GET",
                data: {
                    "Id": id
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.success) {
                        $.post(Url_Add_Item, { "Id": id },
                            function (r) {
                                $("#table_item").empty().append(r);

                            });
                    }
                    else {
                        Utils.OpenNotify("Thông báo", r.message, "warning");
                    }
                },
                error: function (err) {
                    Utils.OpenNotify("Thông báo", err.responseText, "error");
                },
                complete: function () {

                }
            });
        }
        //
        function deleteCart(id) {
            $.post(Url_Delete_Item, { "Id": id },
                function (r) {
                    $("#table_item").empty().append(r);
                    $(".number").each(function () {
                        $(this).number(true, 0, '.', ',');
                    });
                });
        }
        //
        function removeCart(id) {
            $.post(Url_Remove_Item, { "Id": id },
                function (r) {
                    $("#table_item").empty().append(r);
                    $(".number").each(function () {
                        $(this).number(true, 0, '.', ',');
                    });
                });
        }
        //
        function saveCart() {
            Utils.LoadIn();
            var key = $("#txt_orderkey").val();
            var id = $("#txt_orderid").val();
            var desc = $("#txt_description").val();

            $.post(Url_Save_Order, {
                OrderKey: key,
                Id: id,
                Description: desc
            }, function (r) {
                if (!r.success) {
                    Utils.OpenNotify("Thông báo", r.message, "error");
                }
                else {
                    Utils.OpenNotify("Thông báo", "Đã lưu thành công !.", "success");
                    Utils.BackWithRefresh();
                }
            });
        }
        //
        function qtyCart(id) {
            var qty = $("input[key='" + id + "'][name='txt_Qty']").val();
            var pric = $("input[key='" + id + "'][name='txt_ItemPrice']").val();

            $.post(Url_Qty_Item, { "Id": id, "qty": qty, "pric": pric },
                function (r) {
                    $("#table_item").empty().append(r);
                    $(".number").each(function () {
                        $(this).number(true, 0, '.', ',');
                    });
                });
        }
        //
        function Open(id, type) {
            $.ajax({
                url: "/Inventory/Print_Preview",
                type: "GET",
                data: {
                    "OrderKey": id,
                    "ViewType": type
                },
                beforeSend: function () {
                    $("#modal").empty();
                    Utils.LoadIn();
                },
                success: function (r) {
                    $("#modal").append(r);
                },
                error: function (err) {

                },
                complete: function () {
                    Utils.OpenMagnific("#modal");
                    Utils.LoadOut();
                }
            });
        }
    </script>
}

Views/Inventory/Output/List.cshtml
@section styles{
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <style>
        .ranges {
            float: right !important;
        }
    </style>
}
@{
    var _List = new List<Order_Model>();
    if (ViewBag.List != null)
    {
        _List = ViewBag.List as List<Order_Model>;
    }
}
<header class="page-header">
    <h2 class="text-primary">Đơn hàng xuất/ bán</h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
<div class="row">
    <div class="col-md-12">
        <div class="card border">
            <div class="card-header">
                <div class="row">
                    <div class="col-4">
                        <div class="input-group">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt mr-2"></i>
                                Thời gian
                            </span>
                            <input type="text" name="daterange" value="" id="txt_daterange" class="form-control" />
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="input-group">
                            <input type="text" value="" id="txt_Search" name="Name" class="form-control" placeholder="Tìm kiếm" />
                            <button type="button" class="btn btn-default" id="btn_Search">
                                <i class="bx bx-search"></i>
                                Tìm
                            </button>
                        </div>
                    </div>
                    <div class="col-2 text-right">
                        <a asp-controller="Inventory" asp-action="Export_Shopee" class="btn btn-success">
                            <i class="fas fa-file-excel"></i>
                            Xuất Excel
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body" id="divData">
                @await Html.PartialAsync("~/Views/Inventory/Output/_Table_Order.cshtml", _List)
            </div>
        </div>
    </div>
</div>
<input id="txt_StartDate" type="hidden" value="@ViewBag.Start" name="FromDate" />
<input id="txt_EndDate" type="hidden" value="@ViewBag.End" name="ToDate" />
<div id="modal" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
</div>
@section scripts{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>
        var Url_Delete_Output = "@Url.Action("Delete_Output", "Inventory")";
        function Delete(OrderKey) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: Url_Delete_Output,
                                type: "POST",
                                data: {
                                    "OrderKey": OrderKey
                                },
                                beforeSend: function () {
                                },
                                success: function (r) {
                                    if (r.success) {
                                        var elm = $("#" + OrderKey);
                                        Utils.RemoveRow(elm);
                                    }
                                    else {
                                        Utils.OpenNotify(r.message, "Thông báo", "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                                },
                                complete: function () {
                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }
        $(function () {
            var start = $("#txt_StartDate").val();  //
            var end = $("#txt_EndDate").val();     //

            if (start === "") {
                start = Utils.GetFirstDayMonth();
            }
            if (end === "") {
                end = Utils.GetLastDayMonth();
            }

            $("#txt_daterange").daterangepicker({
                locale: {
                    format: "DD/MM/YYYY",
                    "customRangeLabel": "Tuỳ chọn",
                    "applyLabel": "Áp dụng",
                    "cancelLabel": "Huỷ",
                },
                ranges: {
                    "Hôm nay": [moment(), moment()],
                    "Hôm qua": [moment().subtract(1, "days"), moment().subtract(1, "days")],
                    "7 ngày qua": [moment().subtract(6, "days"), moment()],
                    "30 ngày qua": [moment().subtract(29, "days"), moment()],
                    "Tháng này": [moment().startOf("month"), moment().endOf("month")],
                    "Tháng trước": [moment().subtract(1, "month").startOf("month"), moment().subtract(1, "month").endOf("month")]
                },
                "alwaysShowCalendars": true,
                "startDate": start,
                "endDate": end
            }, function (start, end, label) {
                console.log("New date range selected: " + start.format("DD/MM/YYYY") + " to " + end.format("DD/MM/YYYY") + " (predefined range: " + label + ")");
                $("#txt_StartDate").val(start.format("DD/MM/YYYY"));
                $("#txt_EndDate").val(end.format("DD/MM/YYYY"));
                SearchData();
            });
        });
        $("#btn_Search").click(function () {
            SearchData();
        });
        function SearchData() {
            var name = $("#txt_Search").val();
            var from = $("#txt_StartDate").val();
            var to = $("#txt_EndDate").val();
            $.ajax({
                url: "/Inventory/List_Output_Data",
                type: "GET",
                data: {
                    "FromDate": from,
                    "ToDate": to,
                    "Name": name
                },
                beforeSend: function () {
                    $("#divData").empty();
                    Utils.LoadIn();
                },
                success: function (r) {
                    $("#divData").append(r);
                },
                error: function (err) {

                },
                complete: function () {
                    Utils.LoadOut();
                    $(".number").each(function () {
                        $(this).number(true, 0, '.', ',');
                    });
                }
            });
        }
        //
        function Open(id, type) {
            $.ajax({
                url: "/Inventory/Print_Preview",
                type: "GET",
                data: {
                    "OrderKey": id,
                    "ViewType": type
                },
                beforeSend: function () {
                    $("#modal").empty();
                    Utils.LoadIn();
                },
                success: function (r) {
                    $("#modal").append(r);
                },
                error: function (err) {

                },
                complete: function () {
                    Utils.OpenMagnific("#modal");
                    Utils.LoadOut();
                }
            });
        }
    </script>
}