Models/ErrorViewModel.cs
using System;

namespace ShopCP.Models
{
    public class ErrorViewModel
    {
        public string Name { get; set; }
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ConfigController.cs
using Microsoft.AspNetCore.Mvc;
using SDK.Shopee;
using System;
using System.Collections.Generic;
using System.Globalization;

namespace ShopCP.Controllers
{
    public class ConfigController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StockBegin()
        {
            ViewBag.ListProduct = Product_Data.List(UserLog.PartnerNumber, 0, out string Error);
            TempData["Error"] = Error;
            return View();
        }

        [HttpPost]
        public JsonResult Save(List<QtyModel> list, string datestock)
        {
            var zResult = new ServerResult();
            try
            {
                if (DateTime.TryParseExact(datestock, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime zDate))
                {
                    foreach (var rec in list)
                    {
                        var zInfo = new CloseMonth_Info();
                        zInfo.CloseMonth.BeginQty = rec.qty;
                        zInfo.CloseMonth.ProductKey = rec.id;
                        zInfo.CloseMonth.CloseMonth = zDate.ToString("dd/MM");
                        zInfo.CloseMonth.CreatedBy = UserLog.UserKey;
                        zInfo.CloseMonth.ModifiedBy = UserLog.UserKey;
                        zInfo.CloseMonth.CreatedName = UserLog.UserName;
                        zInfo.CloseMonth.ModifiedName = UserLog.UserName;
                        zInfo.CloseMonth.PartnerNumber = UserLog.PartnerNumber;
                        zInfo.Create_ServerKey();
                    }

                    zResult.Success = true;
                }
                else
                {
                    zResult.Success = false;
                    zResult.Message = "Error Date Code";
                }
            }
            catch (Exception ex)
            {
                zResult.Success = false;
                zResult.Message = ex.ToString().GetFirstLine();
            }

            return Json(zResult);
        }

        public IActionResult ListConnect()
        {
            ViewBag.List = Link3rt_Data.List(UserLog.PartnerNumber, out _);
            return View();
        }

        [HttpPost]
        public JsonResult LoginShopee(string Username, string Password, string Otp, string Capcha, string Capchaid)
        {
            var zResult = new ServerResult();
            string Cookies = "";

            Otp ??= "";
            Capcha ??= "";
            Capchaid ??= "";
            string gsession = Guid.NewGuid().ToString();
            ShopeeClient zClient = new(gsession);
            zClient.LoginOTP(Username, Password, Otp, Capcha, Capchaid);

            if (zClient.Message == "481")
            {
                zResult.Success = false;
                zResult.Data = "OTP";
                zResult.Message = "Phải nhập mã OTP";
                return Json(zResult);
            }
            if (zClient.Message == "482")
            {
                zResult.Success = false;
                zResult.Data = "OTP";
                zResult.Message = "OTP không đúng";
                return Json(zResult);
            }
            if (zClient.Message == "470")
            {
                zResult.Success = false;
                zResult.Data = "CAPCHA";
                zResult.Message = "Bạn phải nhập CAPCHA";
                return Json(zResult);
            }
            if (zClient.Message == "490")
            {
                zResult.Success = false;
                zResult.Data = "CAPCHA";
                zResult.Message = "Không đúng CAPCHA";
                return Json(zResult);
            }
            if (zClient.Message == "OK")
            {
                zResult.Data = "OK";
                zResult.Success = true;
                zResult.Message = "Đăng nhập thành công !.";

                Cookies = zClient.GetCookie();

                if (zResult.Success)
                {
                    #region [--Save LOGIN--]
                    var zModel = new Link3rt_Model();
                    zModel.Password = Password;
                    zModel.UserName = Username;
                    zModel.Cookies = Cookies;
                    zModel.Web = "SHOPEE";
                    zModel.PartnerNumber = UserLog.PartnerNumber;
                    zModel.CreatedBy = UserLog.UserKey;
                    zModel.ModifiedBy = UserLog.UserKey;
                    zModel.CreatedName = UserLog.UserName;
                    zModel.ModifiedName = UserLog.UserName;
                    zModel.RecordStatus = 1;

                    var zInfo = new Link3rt_Info(UserLog.PartnerNumber, "SHOPEE");
                    zModel.AutoKey = zInfo.Link3rt.AutoKey;
                    zInfo.Link3rt = zModel;
                    if (zInfo.Code == "404")
                        zInfo.Create_KeyAuto();
                    else
                        zInfo.Update();
                    #endregion
                }

                return Json(zResult);
            }
            if (zClient.Message != string.Empty)
            {
                zResult.Data = "ERR";
                zResult.Success = false;
                zResult.Message = "Thông tin đăng nhập không đúng !.";
                return Json(zResult);
            }

            return Json(zResult);
        }

        [HttpPost]
        public JsonResult StatusShopee()
        {
            var zResult = new ServerResult();
            var zInfo = new Link3rt_Info(UserLog.PartnerNumber, "SHOPEE");
            if (zInfo.Code == "404")
            {
                zResult.Success = false;
                return Json(zResult);
            }
            var zModel = zInfo.Link3rt;
            if (zModel.RecordStatus == 1)
            {
                zModel.RecordStatus = 0;
            }
            else
            {
                zModel.RecordStatus = 1;
            }
            zInfo.Link3rt = zModel;
            zInfo.UpdateStatus();
            zResult.Success = true;
            return Json(zResult);
        }

        [HttpGet]
        public JsonResult GetCapcha()
        {
            var zResult = new ServerResult();
            string gsession = Guid.NewGuid().ToString();
            ShopeeClient zClient = new(gsession);
            zResult.Data = zClient.CapCha().data;
            return Json(zResult);
        }
    }
}

Controllers/Trading/ShopeeController.cs
using ShopCP.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SDK.Shopee;
using System;
using System.Diagnostics;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using Microsoft.Extensions.Logging;

namespace ShopCP.Controllers
{
    public class ShopeeController : BaseController
    {
        private readonly ILogger<ShopeeController> _Logger;
        public ShopeeController(ILogger<ShopeeController> logger)
        {
            _Logger = logger;
        }

        [Route("cua-hang-shopee")]
        public IActionResult Index()
        {
            var zInfo = new Link3rt_Info(UserLog.PartnerNumber, "SHOPEE");
            if (zInfo.Code == "404" || zInfo.Link3rt.RecordStatus == 0)
            {
                TempData["Error"] = "Bạn chưa liên kết Shopee !.";
            }
            else
            {
                string Username = zInfo.Link3rt.UserName;
                string Password = zInfo.Link3rt.Password;
                string Cook = zInfo.Link3rt.Cookies;

                string gsession = Guid.NewGuid().ToString();
                ShopeeClient zClient = new(gsession, Cook);
                var zRoot = zClient.LoginOTP(Username, Password);

                if (zRoot.data == null)
                {
                    TempData["Error"] = zClient.Message;
                }

                ViewBag.ShopName = zRoot.data.display_name;
                ViewBag.ShipId = zRoot.data.shopid;

                var ssShopee = new ShopeeSession();
                ssShopee.GSession = gsession;
                ssShopee.Cookie = zClient.GetCookie();
                ssShopee.ShopId = zRoot.data.shopid;
                ssShopee.ShopName = zRoot.data.display_name;

                HttpContext.Session.SetString("Jss", JsonConvert.SerializeObject(ssShopee));

                var zRootShipper = zClient.GetShipperList();
                ViewBag.Shipper = zRootShipper.data;
            }

            return View();
        }

        [Route("soan-don-hang/{Id}")]
        public IActionResult Prepare_Order(long Id)
        {
            string Jss = HttpContext.Session.GetString("Jss");
            var Sspe = JsonConvert.DeserializeObject<ShopeeSession>(Jss);

            ShopeeClient zClient = new(Sspe.GSession, Sspe.Cookie);
            var zRoot = zClient.OrderInfo(Id);
            var zTimeSlot = zClient.GetTimeSlot(Id);
            var zAddress = zClient.GetAddress(Id);

            ViewBag.TimeSlot = zTimeSlot.data;
            ViewBag.PickupAddress = zAddress.data;

            TempData["PostInit"] = JsonConvert.SerializeObject(zTimeSlot.PostInit);

            Order_Model zOrder = new();
            zOrder.OrderDate = TN_Utils.UnixTimeStampToDateTime(zRoot.data.create_time);
            zOrder.BuyerName = zRoot.data.buyer_address_name;
            zOrder.BuyerPhone = zRoot.data.buyer_address_phone;
            zOrder.ShippingAddress = zRoot.data.shipping_address;
            zOrder.S_OrderID = zRoot.data.order_sn;
            zOrder.S_JSON = JsonConvert.SerializeObject(zRoot.data);
            zOrder.PartnerNumber = UserLog.PartnerNumber;

            #region [--Auto Map Data--]
            foreach (var rec in zRoot.data.order_items)
            {
                var sku = rec.item_model.sku;
                if (sku.Length > 0)
                {
                    var zInfo = new Product_Info();

                    //ƯU TIÊN - kiểm tra gói sản phẩm
                    var zPag = new Package_Info(sku, true);
                    if (zPag.Code == "200")
                    {
                        //get danh sách sản phẩm trong gói
                        var list = Package_Item_Data.List(UserLog.PartnerNumber, zPag.Package.PackageKey, out _);
                        foreach (var p in list)
                        {
                            zInfo = new Product_Info(p.ItemKey);
                            if (zInfo.Code == "200")
                            {
                                var Product = zInfo.Product;
                                var outqty = rec.amount;
                                var checkqty = Product_Data.GetStock(Product.ProductKey);
                                //kiểm tra số lượng trước khi add vào danh sách
                                if (outqty <= checkqty)
                                {
                                    var zItem = new Order_Item_Model();
                                    zItem.ItemKey = p.ItemKey;
                                    zItem.ItemName = p.ItemName;
                                    zItem.ItemQty = rec.amount;
                                    zItem.ItemPhoto = p.ItemPhoto;
                                    zItem.ItemPrice = Product.SalePrice;
                                    zItem.ItemMoney = rec.amount * Product.SalePrice;
                                    zOrder.ListItem.Add(zItem);
                                }
                            }
                        }
                    }

                    //kiem tra sản phẩm
                    zInfo = new Product_Info(sku, true);
                    if (zInfo.Code == "200")
                    {
                        var Product = zInfo.Product;
                        var outqty = rec.amount;
                        var checkqty = Product_Data.GetStock(Product.ProductKey);
                        //kiểm tra số lượng trước khi add vào danh sách
                        if (outqty <= checkqty)
                        {
                            var zItem = new Order_Item_Model();

                            zItem.ItemKey = Product.ProductKey;
                            zItem.ItemName = Product.ProductName;
                            zItem.ItemQty = rec.amount;
                            zItem.ItemPhoto = Product.PhotoPath;
                            zItem.ItemPrice = Product.SalePrice;
                            zItem.ItemMoney = rec.amount * Product.SalePrice;
                            zOrder.ListItem.Add(zItem);
                        }
                        else
                        {
                            TempData["Error"] += "[" + Product.ProductName + "] đã hết tồn kho, ";
                        }
                    }
                }
            }

            // xử lý trùng sản phẩm
            #region [------]
            var listex = zOrder.ListItem;
            listex = listex
   .GroupBy(i => i.ItemKey)
   .Select(g => new Order_Item_Model
   {
       ItemKey = g.Key,
       ItemName = g.Select(i => i.ItemName).First(),
       ItemQty = g.Sum(i => i.ItemQty),
       ItemPhoto = g.Select(i => i.ItemPhoto).First(),
       ItemPrice = g.Select(i => i.ItemPrice).First(),
       ItemMoney = g.Sum(i => i.ItemMoney),
   })
   .ToList();
            zOrder.ListItem = listex;
            #endregion

            HttpContext.Session.SetString("Order", JsonConvert.SerializeObject(zOrder));
            ViewBag.LocalOrder = zOrder;
            #endregion

            return View(zRoot.data);
        }

        //[HttpPost]
        //public JsonResult Update_ShopeeProduct(string ProductKey)
        //{
        //    var zResult = new ServerResult();
        //    var zInfo = new Product_Info(ProductKey);
        //    if (zInfo.Code != "404")
        //    {
        //        var zProduct = zInfo.Product;

        //        string file = Url.Content(zProduct.PhotoPath);
        //        byte[] fileb = TN_Helper.GetBytes(new FileStream(file, FileMode.Open, FileAccess.Read));

        //        string Jss = HttpContext.Session.GetString("Jss");
        //        var Sspe = JsonConvert.DeserializeObject<ShopeeSession>(Jss);
        //        ShopeeClient zClient = new(Sspe.GSession, Sspe.Cookie);
        //        string imgId = zClient.UploadImage(TN_Utils.RandomString(10), fileb);

        //        bool isExist = false;

        //        #region [Tạo sản phẩm để post shopee] các thông số bắt buột
        //        var ProductPost = new SDK.Shopee.Root_ProductPost.Root();
        //        // không nhãn hiệu
        //        ProductPost.brand_id = 0;
        //        // mô tả sản phẩm
        //        ProductPost.description = zProduct.Description.StripHtml(); //bỏ html tag ở database ngoài
        //        // tên sản phẩm
        //        ProductPost.name = zProduct.ProductName;
        //        // giá bán
        //        ProductPost.price = zProduct.SalePrice.ToString();
        //        // tồn kho
        //        ProductPost.stock = Convert.ToInt64(Product_Data.GetStock(ProductKey));
        //        // cân nặng đơn vị tính bằng gr
        //        ProductPost.weight = "500";
        //        // ẩn hiện sp
        //        ProductPost.unlisted = false;
        //        #endregion


        //    }
        //    else
        //    {
        //        zResult.Success = false;
        //        zResult.Message = "Local product error vui lòng liên hệ IT !.";
        //    }
        //    return Json(zResult);
        //}

        [HttpGet]
        public IActionResult Get_Category(int id = 0)
        {
            var zlist = new List<SDK.Shopee.Root_Category.List>();
            string catSp = HttpContext.Session.GetString("Cate");
            if (catSp == null)
            {
                ShopeeClient zClient;
                string Jss = HttpContext.Session.GetString("Jss");
                if (Jss == null)
                {
                    var zInfo = new Link3rt_Info(UserLog.PartnerNumber, "SHOPEE");
                    string Username = zInfo.Link3rt.UserName;
                    string Password = zInfo.Link3rt.Password;
                    string Cook = zInfo.Link3rt.Cookies;

                    string gsession = Guid.NewGuid().ToString();
                    zClient = new(gsession, Cook);
                    var zLog = zClient.LoginOTP(Username, Password);

                    if (zLog.data == null)
                    {

Views/Shopee/Index.cshtml
@using SDK.Shopee.Root_ShipmentList
@{
    var _ShipperList = new List<Datum>();
    if (ViewBag.Shipper != null)
    {
        _ShipperList = ViewBag.Shipper as List<Datum>;
    }
}
@section Styles{
    <style>
        @@media only screen and (max-width: 991px) {
            .table.table-no-more td {
                padding-left: 30% !important;
            }

            .table.table-no-more tr {
                padding-bottom: 10px !important;
            }
        }

        #cbo_shipper .select2-selection--single {
            height: 100% !important;
        }

        #cbo_shipper .select2-selection__rendered {
            word-wrap: break-word !important;
            text-overflow: inherit !important;
            white-space: normal !important;
        }
    </style>
}
<header class="page-header">
    <h2 class="text-primary">
        <a asp-controller="Shopee" asp-action="Index">@ViewBag.ShopName</a>
    </h2>
    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="#">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
<section class="content-with-menu mailbox">
    <div class="content-with-menu-container">
        @if (TempData["Error"] != null && TempData["Error"].ToString() != string.Empty)
        {
            <div class="alert alert-warning">
                @TempData["Error"].ToString()
                <br />
                Vào cài đặt > <a asp-controller="Config" asp-action="ListConnect">Liên kết shop</a> và chọn Shopee để liên kết tài khoản.
            </div>
        }
        else
        {
            <div class="inner-menu-toggle">
                <a href="#" class="inner-menu-expand" data-open="inner-menu">
                    Show Menu
                    <i class="fas fa-chevron-right"></i>
                </a>
            </div>
            <menu id="content-menu" class="inner-menu" role="menu">
                <div class="nano">
                    <div class="nano-content">
                        <div class="inner-menu-toggle-inside">
                            <a href="#" class="inner-menu-collapse">
                                <i class="fas fa-chevron-up d-inline-block d-md-none"></i>
                                <i class="fas fa-chevron-left d-none d-md-inline-block"></i>
                                Hide Menu
                            </a>
                            <a href="#" class="inner-menu-expand" data-open="inner-menu">
                                Show Menu
                                <i class="fas fa-chevron-down"></i>
                            </a>
                        </div>
                        <div class="inner-menu-content">
                            <div class="sidebar-widget m-0">
                                <div class="widget-header">
                                    <h6 class="title">Chờ lấy hàng</h6>
                                    <span class="widget-toggle">+</span>
                                </div>
                                <div class="widget-content" style="">
                                    <ul class="list-unstyled mailbox-bullets">
                                        <li>
                                            <a href="#all" class="menu-item" onclick="Get_List('all',1,0)">
                                                Tất cả
                                                <span class="float-right badge badge-primary" id="all"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#to_process" class="menu-item" onclick="Get_List('to_process',1,0)">
                                                Chưa xử lý
                                                <span class="float-right badge badge-primary" id="to_process"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#processed" class="menu-item" onclick="Get_List('processed',1,0)">
                                                Đã xử lý
                                                <span class="float-right badge badge-primary" id="processed"></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <hr class="separator">
                            <div class="sidebar-widget m-0">
                                <div class="widget-header">
                                    <h6 class="title">Mặt hàng</h6>
                                    <span class="widget-toggle">+</span>
                                </div>
                                <div class="widget-content">
                                    <ul class="list-unstyled mailbox-bullets">
                                        <li>
                                            <a href="#productimport" class="menu-item" onclick="Get_Product()">Cần xử lý</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </menu>
            <div class="inner-body mailbox-folder">
                <div id="ajaxloading" style="background: rgb(52, 152, 219);display: none;position: absolute;width: 100%;height: 100%;z-index: 1000;">
                    <div class="book">
                        <div class="book__page"></div>
                        <div class="book__page"></div>
                        <div class="book__page"></div>
                    </div>
                </div>
                <div class="mailbox-actions p-2" id="divSearch">
                    <div class="row">
                        <div class="col-9"></div>
                        <div class="col-3">
                            <select id="cbo_shipper" class="select2">
                                @{
                                    <option value="0" selected>Vận chuyển</option>
                                    foreach (var rec in _ShipperList)
                                    {
                                        if (rec.category_id == 10008)
                                        {
                                            <option value="@rec.channel_id">@rec.display_name</option>
                                        }
                                        else
                                        {
                                            <option value="@rec.category_id">@rec.display_name</option>
                                        }
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="mailbox-email-list" style="top:60px !important">
                    <div class="nano">
                        <div class="nano-content" id="divViewData">

                        </div>
                    </div>
                </div>
                <div class="mailbox-actions p-0" style="position: absolute; bottom: 0px; width: 100%; background: white; text-align: center; border-top: 5px solid #e2e3e6;" id="divPager">

                </div>
            </div>
        }
    </div>
</section>
<div id="modal" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
</div>
<input type="hidden" value="@ViewBag.Message" id="txt_Message" />
<input type="hidden" value="" id="totalItems" />
<input type="hidden" value="" id="option" />
<input type="hidden" value="" id="page" />
@section Scripts{
    <script src="~/js-app/Shopee.js"></script>
    <script>

    </script>
}

Views/Shopee/_Category.cshtml
@model List<SDK.Shopee.Root_Category.List>
@{
    Layout = null;
}

@if (Model.Count > 0)
{
    <ul class="list-unstyled col-4" style="max-height: 400px; overflow-y: auto;">
        @foreach (var rec in Model)
        {
            if (rec.is_prohibit)
            {
                <li style="cursor: not-allowed; background: #9e9e9e61" id="@rec.id" class="p-2">
                    <b>@rec.display_name</b>
                    @if (rec.has_children)
                    {
                        <span class="float-right"><i class='bx bxs-right-arrow'></i></span>
                    }
                </li>
            }
            else
            {
                <li style="cursor:pointer" id="@rec.id" class="p-2" onclick="CateShopee(@rec.id)">
                    <b>@rec.display_name</b>
                    @if (rec.has_children)
                    {
                        <span class="float-right"><i class='bx bxs-right-arrow'></i></span>
                    }
                </li>
            }
        }
    </ul>
}

Views/Shopee/_Commit.cshtml
@using Newtonsoft.Json
@model Product_Model
@{
    Layout = null;
}
<div class="card">
    <div class="card-header">
        <h2 class="card-title">Thông tin sản phẩm sẽ cập nhật lên shopee</h2>
    </div>
    <div class="card-body">
        <div class="tabs">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-target="#popular" href="#popular" data-toggle="tab">
                        <i class="fas fa-star"></i>
                        Nhóm ngành hàng
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-target="#recent" href="#recent" data-toggle="tab">Thông tin sản phẩm</a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="popular" class="tab-pane active">
                    <div class="row flex-row flex-nowrap" id="divCate" style="overflow-x:auto">

                    </div>
                </div>
                <div id="recent" class="tab-pane">
                    <div class="form-group-sm mb-1 row">
                        <label class="control-label col-2">Hình ảnh</label>
                        <div class="col-10">
                            <div class="popup-gallery">
                                @{
                                    <div class="float-left mb-1 pt-1 mr-1 picView">
                                        <a class="" href="@Model.PhotoPath" title="">
                                            <div class="img-fluid">
                                                <img src="@Url.Content(Model.PhotoPath)" width="105" height="105">
                                            </div>
                                        </a>
                                    </div>
                                    var ListPicture = JsonConvert.DeserializeObject<List<Product_Photo_Model>>(Model.PhotoList);
                                    foreach (var rec in ListPicture)
                                    {
                                        <div class="float-left mb-1 pt-1 mr-1 picView">
                                            <a class="" href="@rec.PhotoPath" title="">
                                                <div class="img-fluid">
                                                    <img src="@Url.Content(rec.PhotoPath)" width="105" height="105">
                                                </div>
                                            </a>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="form-group-sm mb-1 row">
                        <label class="control-label col-2">Tên sản phẩm</label>
                        <div class="col-10">
                            <input type="text" class="form-control" value="@Model.ProductName" name="ProductName" id="txt_ProductName" />
                        </div>
                    </div>
                    <div class="form-group-sm mb-1 row">
                        <label class="control-label col-2">Thương hiệu</label>
                        <div class="col-4">
                            <input type="text" class="form-control" name="brand_id" shopeeval="0" placeholder="" value="NoBrand" disabled id="txt_Brand"/>
                        </div>
                        <label class="control-label col-2">Cân nặng sau khi gói (gr)</label>
                        <div class="col-4">
                            <input type="text" class="form-control" value="@Model.Weight" name="Weight" id="txt_Weight" />
                        </div>
                    </div>
                    <div class="form-group-sm mb-1 row">
                        <label class="control-label col-2">SKU</label>
                        <div class="col-4">
                            <input type="text" class="form-control" value="@Model.SKU" name="SKU" id="txt_SKU" />
                        </div>
                        <label class="control-label col-2">Giá bán</label>
                        <div class="col-4">
                            <input type="text" class="form-control number" value="@Model.SalePrice" name="SalePrice" id="txt_SalePrice" />
                        </div>
                    </div>
                    <div class="form-group-sm mb-1 row">
                        <label class="control-label col-2">Mô tả</label>
                        <div class="col-10">
                            <textarea class="form-control" name="Description" placeholder="" required="" id="txt_Description">@Model.Description.StripHtml()</textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <button type="button" class=" btn btn-primary float-right" onclick="PushShopee('@Model.ProductKey')">
            Cập nhật
        </button>
        <button type="button" class=" btn btn-default modal-dismiss " >
            Huỷ & đóng
        </button>
    </div>
</div>

Views/Shopee/_Error.cshtml
@model ErrorViewModel
<div class="alert alert-danger">
    <strong>Có vấn đề phát sinh !</strong> mã @Model.RequestId
</div>